### ISSUE TITLE
Meta-issue for Q1

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#569]
This meta-issue summarizes the features that we promised to deliver by the end of Q1 in the proposal.

We have to test two hypotheses in Q1:

 - Can protocol designers effectively specify, test and disseminate Cosmos protocols in Quint + markdown comments instead of just markdown?
 - Can Cosmos engineers effectively understand protocols in Quint + markdown comments and make them useful in their work?

We promised to deliver the following features:

 - [ ] Tutorials and onboarding documentation on Quint and specification writing.
 - [ ] Support for installation and onboarding of Quint by protocol designers and engineers.
 - [ ] First specifications are written in Quint and integrated into continuous integration of Interchain product teams.
 - [ ] Integration with Apalache
 - [ ] Implementation of the missing language features:
   - [ ] import from files,
   - [ ] higher-order definitions,
   - [ ] discriminated unions,
   - [ ] runs,
   - [ ] constants,
   - [ ] assumptions,
   - [ ] temporal operators,
   - [ ] a few operators on sets
 - [ ] Finishing the effects checker beyond the prototype.
 - [ ] User survey on the syntax of Quint and tooling around it.
 - [ ] Automatic generation of markdown documentation
 - [ ] Improving the VSCode plugin with auto-completion, code navigation, overlay documentation, and type hints.
 - [ ] Continuous delivery and tool packaging
 - [ ] Syntax and tool improvements after receiving the feedback from the first users.
 - [ ] Experiments on the full cycle comprising: specification, interactive debugging, randomized simulation, symbolic simulation, and model checking.
 - [ ] A specification dashboard to assist protocol designers when their specifications break.
 - [ ] Support ITF traces in the Quint simulator (Informal Trace Format).
 - [ ] Improve error reporting by adding hints to reported errors, and selecting which errors to report when there are multiple ones.
