### ISSUE TITLE
Usability feedback

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#723]
I have been talking to our first users of Quint, who are writing real specs. Here is the summary of the recent feedback:

@lasarojc gave us feedback earlier in #440, so this is a diff:

 - [ ] Something like Jupyter notebooks would be great. Using `lmt` at the moment is ok.
 - [ ] Need for instances. This is ongoing work: [ADR006](https://github.com/informalsystems/quint/blob/main/doc/adr006-modules.lit.md), #528, #237, 236
 - [ ] Update the tutorials with `test` and `run`: https://github.com/informalsystems/quint/pull/721
 - [ ] Support for refinement proofs?

@josef:

 - [ ] It is not clear how to start from a clean slate. A command to generate an empty spec?
 - [ ] `quint -r p2p.qnt::p2p` is not intuitive
 - [x] `.reload` in REPL is great
 - [ ] `const` is not supported yet, confusing. The same chunk of work on instances
 - [x] have to write `if (P) A else true`, because `implies` is not lazy: #717
 - [ ] Random simulation is a bit slow on `p2p`, about 2 min
 - [ ] Writing `x' = x` is pain, need `unchanged`
 - [ ] Non-deterministic tests should be run multiple times: #678
 - [ ] The semantic of actions is not clear at first, Josef wanted to write functions, which are written with `def`

@ivan-gavran:

- [ ] Show the intermediate values or let the user print them: #677
